import type { AppNode, AppEdge } from '../../types/graph'
import type { LoadedDataset } from '../../store/useDatasetStore'
import type { TrainingConfig } from '../../types/training'
import type { CompileResult } from './types'
import { parsePipelineNodes } from './pipelineGraph'
import { generatePipelinePython } from './compilePipeline'

function pyStr(s: string): string {
  return JSON.stringify(s)
}

function xgbHyperparamsBlock(config: TrainingConfig, task: 'classification' | 'regression'): string[] {
  const lines: string[] = [
    'model_kw = dict(',
    `    n_estimators=${config.xgbNEstimators},`,
    `    max_depth=${config.xgbMaxDepth},`,
    `    learning_rate=${config.xgbLearningRate},`,
    `    subsample=${config.xgbSubsample},`,
    `    colsample_bytree=${config.xgbColsampleBytree},`,
    `    min_child_weight=${config.xgbMinChildWeight},`,
    `    gamma=${config.xgbGamma},`,
    `    reg_alpha=${config.xgbRegAlpha},`,
    `    reg_lambda=${config.xgbRegLambda},`,
    '    random_state=42,',
    '    verbosity=0,',
    '    n_jobs=1,',
  ]
  if (config.xgbEarlyStoppingRounds > 0) {
    lines.push(`    early_stopping_rounds=${config.xgbEarlyStoppingRounds},`)
  }
  if (task === 'regression') {
    const obj = config.xgbObjective || 'reg:squarederror'
    lines.push(`    objective=${pyStr(obj)},`)
    lines.push('    eval_metric="rmse",')
  } else {
    lines.push('    objective="binary:logistic" if len(np.unique(y_train)) == 2 else "multi:softmax",')
    lines.push('    eval_metric=["logloss", "error"],')
    lines.push(')')
    lines.push('if model_kw["objective"] == "multi:softmax":')
    lines.push('    model_kw["num_class"] = len(np.unique(y_train))')
    return lines
  }
  lines.push(')')
  return lines
}

export function compileXGBoost(
  dataset: LoadedDataset | null,
  targetColumn: string | null,
  pipelineNodes: AppNode[],
  pipelineEdges: AppEdge[],
  config: TrainingConfig,
): CompileResult {
  const errors: string[] = []
  const warnings: string[] = []
  const task = config.xgbTask

  if (!dataset) {
    return { code: '', errors: ['No dataset loaded.'], warnings, filename: 'xgboost_train.py', label: 'Generated XGBoost Script' }
  }
  if (!targetColumn) {
    return { code: '', errors: ['No target column selected.'], warnings, filename: 'xgboost_train.py', label: 'Generated XGBoost Script' }
  }
  if (!dataset.columns.find((c) => c.name === targetColumn)) {
    return { code: '', errors: [`Target column "${targetColumn}" not found.`], warnings, filename: 'xgboost_train.py', label: 'Generated XGBoost Script' }
  }
  if (pipelineNodes.filter((n) => n.type === 'datasetSource').length === 0) {
    errors.push('Pipeline has no Source node.')
  }
  if (config.xgbEarlyStoppingRounds > 0 && config.xgbEarlyStoppingRounds >= config.xgbNEstimators) {
    errors.push('early_stopping_rounds must be less than n_estimators.')
  }
  if (errors.length > 0) {
    return { code: '', errors, warnings, filename: 'xgboost_train.py', label: 'Generated XGBoost Script' }
  }

  const { filters, config: pipeConfig } = parsePipelineNodes(pipelineNodes, pipelineEdges)
  const { lines: preprocessLines, imports } = generatePipelinePython({
    dataset,
    targetColumn,
    filters,
    config: pipeConfig,
    task,
    forTraining: true,
  })

  imports.add('import xgboost as xgb')
  if (task === 'regression') {
    imports.add('from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score')
  }

  const importLines = [...imports].sort()
  const dataPath = dataset.name.replace(/\\/g, '/')
  const safeName = dataset.name.replace(/\.[^.]+$/, '').replace(/\s+/g, '_').toLowerCase()

  const trainBlock = task === 'regression'
    ? [
        'model = xgb.XGBRegressor(**model_kw)',
        'model.fit(',
        '    X_train, y_train,',
        '    eval_set=[(X_train, y_train), (X_val, y_val)],',
        '    verbose=False,',
        ')',
        '',
        'y_pred = model.predict(X_val)',
        'rmse = float(np.sqrt(mean_squared_error(y_val, y_pred)))',
        'mae = float(mean_absolute_error(y_val, y_pred))',
        'r2 = float(r2_score(y_val, y_pred))',
        'print(f"Val RMSE: {rmse:.4f}  MAE: {mae:.4f}  R²: {r2:.4f}")',
      ]
    : [
        'model = xgb.XGBClassifier(**model_kw)',
        'model.fit(',
        '    X_train, y_train,',
        '    eval_set=[(X_train, y_train), (X_val, y_val)],',
        '    verbose=False,',
        ')',
        '',
        'train_acc = float(model.score(X_train, y_train))',
        'val_acc = float(model.score(X_val, y_val))',
        'print(f"Train accuracy: {train_acc:.4f}  Val accuracy: {val_acc:.4f}")',
      ]

  const code = [
    '"""',
    'Generated by Oneiros — XGBoost training script',
    `Dataset: ${dataset.name}`,
    `Target: ${targetColumn}`,
    `Task: ${task}`,
    '"""',
    '',
    ...importLines,
    '',
    `DATA_PATH = ${pyStr(dataPath)}  # update path to your CSV/JSON export`,
    'MODEL_PATH = "xgboost_model.json"',
    '',
    'def load_data(path: str) -> pd.DataFrame:',
    '    if path.lower().endswith(".json"):',
    '        return pd.read_json(path)',
    '    return pd.read_csv(path)',
    '',
    'def main():',
    '    df = load_data(DATA_PATH)',
    '    print(f"Loaded {len(df)} rows from {DATA_PATH}")',
    '',
    ...preprocessLines.map((l) => (l ? `    ${l}` : '')),
    '',
    '    # XGBoost hyperparameters',
    ...xgbHyperparamsBlock(config, task).map((l) => `    ${l}`),
    '',
    ...trainBlock.map((l) => `    ${l}`),
    '',
    '    model.save_model(MODEL_PATH)',
    '    print(f"Model saved to {MODEL_PATH}")',
    '',
    '    # Top feature importances',
    '    imp = sorted(zip(feature_cols, model.feature_importances_), key=lambda x: -x[1])[:10]',
    '    for name, score in imp:',
    '        print(f"  {name}: {score:.4f}")',
    '',
    'if __name__ == "__main__":',
    '    main()',
    '',
  ].join('\n')

  if (pipeConfig.balanceClasses && task === 'regression') {
    warnings.push('Balance Classes node is ignored for regression tasks.')
  }

  return {
    code,
    errors,
    warnings,
    filename: `${safeName}_xgboost.py`,
    label: 'Generated XGBoost Script',
  }
}
